name: Wiki Update Demo
run-name: Pushing Updates to BTA Wiki
on:
    push:
      branches:
        - wiki
jobs:
    post-to-wiki:
        name: Post Updates to Wiki
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository }}
                path: bta
            - name: Check out automation code
              uses: actions/checkout@v4
              with:
                repository: 'BattleTech-Advanced-3062/bta-wiki-automation'
                path: wiki-gen
                ref: 'parser'
            - name: Run Faction automation
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/factionRenderer.py
            - name: Run Factory automation
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                python3 /home/runner/work/BattleTech-Advanced/BattleTech-Advanced/wiki-gen/src/factoryRenderer.py